### ISSUE TITLE
[BUG} Resnet benchmark on grayskull e75

### ISSUE THREAD

**Issue by refill-dn** [tenstorrent/benchmarking#24]
**Describe the bug**
I tried to resnet benchmark on grayskull e75. 

**To Reproduce**
Just RUN

(tt-buda env) $ python benchmark.py -d tt -m resnet -c resnet50 --task image_classification -mb 64 --loop_count 32 -opt 4 --save_output

**Expected behavior**
benchmark result.

**Screenshots**
![image](https://github.com/tenstorrent/benchmarking/assets/150002370/176c1d4d-14e9-4db5-84bd-941d4b57b894)

![image](https://github.com/tenstorrent/benchmarking/assets/150002370/26d59701-6255-4e8b-ada3-bfe86bd92d35)

**System (please complete the following information):**
 - Device: E75
 - Host information:  AMD Ryzen 5 7600
 - OS : Ubuntu 22.04
 - Version : ?

**Additional context**

**Comment by milank94** [comment]
Hi @refill-dn 

Please check if you are running the latest stable release for Ubuntu 22.04. Here is the package you can download: https://github.com/tenstorrent/tt-buda/releases/download/v0.12.3/pybuda-gs-v0.12.3-ubuntu-22-04-amd64-python3.10.zip

Setup instructions: https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md

Repo: https://github.com/tenstorrent/benchmarking/tree/v0.12.3

**Comment by milank94** [comment]
@refill-dn Were you able to make any progress with the provided guidance?

**Comment by refill** [comment]
@milank94  : it works! thank you.

*****************************************************
 Device: Grayskull
 Total compilation time (s): 33.8485
 Peak host memory usage (MB): 4607.18
 Total runtime (s) for 30720 inputs: 26.2231
 Samples/sec: 1171.48
 Inference time (ms): 0.9
 Evaluation Score: 0.7885416666666667
 Batch size: 64
 Input shape: 3x224x224
 Datatype: Fp16_b
 Host device: AMD Ryzen 5 7600 6-Core Processor
 PyBUDA Version: 0.1.240509+dev.gs.a84d92c
 PyBUDA Version Date:
