### ISSUE TITLE
[BUG} 

### ISSUE THREAD

**Issue by refill-dn** [tenstorrent/benchmarking#25]
**Describe the bug**

mobilenetv3 benchmark is not work.

**To Reproduce**
I just running benchmark script : 

$ python benchmark.py -d tt -m mobilenetv3 -c lg --task image_classification -mb 64 -mf HiFi3 --loop_count 32 -opt 4 --save_output

**Expected behavior**
get benchmark result.

**Screenshots**

this is log
--------------------------------------------------------------------------------------------------------------------------------------------
2024-05-23 13:53:39.178 | INFO     | Runtime         - Compiling Firmware for TT device
2024-05-23 13:53:54.229 | INFO     | Runtime         - Compile result: FAILURE, failure_type: undefined, device_id: 0, temporal_epoch_id: 0, graph: , logical_core_x: 0, logical_core_y: 0, failure_target:
2024-05-23 13:53:54.229 | ERROR    | Always          - Build ckernels/src failed for a thread 0 with CKernels 'chlkc_unpack'
In file included from /home/dn-dev/tt-buda/third_party/budabackend//src/ckernels/grayskull/buda/common/inc/chlkc_list.h:59,
                 from src/ckernel_main.cc:12,
                 from src/ckernel_unity.cc:8:
/tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/chlkc_unpack_tile_dims.h:35:1: error: too many initializers for 'const uint32_t [24]' {aka 'const long unsigned int [24]'}
   35 | };
      | ^
make[1]: *** [/home/dn-dev/tt-buda/third_party/budabackend//src/firmware/riscv/toolchain/riscv.mk:245: /tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/tensix_thread0/ckernel_unity.o] Error 1
make: *** [Makefile:91: build] Error 2

Log: /tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/hlk_ckernels_compile_thread0.log
Error: /tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/hlk_ckernels_compile_thread0.err.log
2024-05-23 13:53:54.229 | INFO     | pybuda.backend:__init__:85 - Backend compile False, target: , error type: BackendCompileFailure.Invalid, error: Build ckernels/src failed for a thread 0 with CKernels 'chlkc_unpack'
In file included from /home/dn-dev/tt-buda/third_party/budabackend//src/ckernels/grayskull/buda/common/inc/chlkc_list.h:59,
                 from src/ckernel_main.cc:12,
                 from src/ckernel_unity.cc:8:
/tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/chlkc_unpack_tile_dims.h:35:1: error: too many initializers for 'const uint32_t [24]' {aka 'const long unsigned int [24]'}
   35 | };
      | ^
make[1]: *** [/home/dn-dev/tt-buda/third_party/budabackend//src/firmware/riscv/toolchain/riscv.mk:245: /tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/tensix_thread0/ckernel_unity.o] Error 1
make: *** [Makefile:91: build] Error 2

Log: /tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/hlk_ckernels_compile_thread0.log
Error: /tmp/dn-dev/f078973afe83/graph_fwd_0_5/op_2/hlk_ckernels_compile_thread0.err.log
target chip id: 0, target core(x,y): 0 0, temporal epoch id: 0
requires extra size bytes: 0

2024-05-23 13:53:54.230 | FATAL    | Always          - Attempting to read device aiclk when cluster device state is set to idle
2024-05-23 13:53:54.230 | ERROR    | Always          - Attempting to read device aiclk when cluster device state is set to idle
backtrace:
 --- tt_cluster::get_all_device_aiclks()
 --- tt_runtime::query_all_device_aiclks(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
 --- tt_runtime::finish()
 --- /home/dn-dev/tt-buda/pybuda/pybuda/_C.so(+0x972bff) [0x7f1a2a1f3bff]
 --- /home/dn-dev/tt-buda/pybuda/pybuda/_C.so(+0x2c6a36) [0x7f1a29b47a36]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(+0x15a10e) [0x55f57f5c210e]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyObject_MakeTpCall+0x25b) [0x55f57f5b8a7b]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(+0x168acb) [0x55f57f5d0acb]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x614a) [0x55f57f5b0cfa]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f57f5c29fc]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x8ac) [0x55f57f5ab45c]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyObject_FastCallDictTstate+0xc4) [0x55f57f5b7c14]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(+0x164b05) [0x55f57f5ccb05]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyObject_MakeTpCall+0x1fc) [0x55f57f5b8a1c]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x64e6) [0x55f57f5b1096]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f57f5c29fc]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x8ac) [0x55f57f5ab45c]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f57f5c29fc]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x8ac) [0x55f57f5ab45c]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(+0x16893e) [0x55f57f5d093e]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x2a27) [0x55f57f5ad5d7]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f57f5c29fc]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x8ac) [0x55f57f5ab45c]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f57f5c29fc]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x8ac) [0x55f57f5ab45c]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f57f5c29fc]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x6bd) [0x55f57f5ab26d]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x55f57f5c29fc]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_PyEval_EvalFrameDefault+0x198c) [0x55f57f5ac53c]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(+0x13f9c6) [0x55f57f5a79c6]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(PyEval_EvalCode+0x86) [0x55f57f69d256]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(+0x260108) [0x55f57f6c8108]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(+0x2599cb) [0x55f57f6c19cb]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(PyRun_StringFlags+0x81) [0x55f57f6baab1]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(PyRun_SimpleStringFlags+0x41) [0x55f57f6ba961]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(Py_RunMain+0x375) [0x55f57f6b9b15]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(Py_BytesMain+0x2d) [0x55f57f69002d]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f1aac9f4d90]
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f1aac9f4e40]
 --- /home/dn-dev/tt-buda/build/python_env/bin/python(_start+0x25) [0x55f57f68ff25]

2024-05-23 13:53:54.230 | INFO     | Debuda          - Debug server ended on
2024-05-23 13:53:54.233 | WARNING  | pybuda.compile:handle_backend_error:1168 - Compile failed, retrying compilation with different parameters. Retry count: 1
2024-05-23 13:53:54.234 | ERROR    | pybuda.device:run_next_command:469 - Compile error: Backend compile failed: BackendCompileFailure.Invalid
Traceback (most recent call last):
  File "/home/dn-dev/tt-buda/pybuda/pybuda/ttdevice.py", line 832, in compile_for
    self.backend_api = BackendAPI(
  File "/home/dn-dev/tt-buda/pybuda/pybuda/backend.py", line 89, in __init__
    raise BackendCompileException(self.compile_result)
pybuda.backend.BackendCompileException: <pybuda._C.backend_api.BackendCompileResult object at 0x7f19c4e87cb0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dn-dev/tt-buda/pybuda/pybuda/device.py", line 458, in run_next_command
    ret = self.compile_for(
  File "/home/dn-dev/tt-buda/pybuda/pybuda/ttdevice.py", line 858, in compile_for
    raise RuntimeError(f"Backend compile failed: {ex.compile_result.failure_type}")
RuntimeError: Backend compile failed: BackendCompileFailure.Invalid

Error encountered while running benchmark:  Backend compile failed: BackendCompileFailure.Invalid
Traceback (most recent call last):
  File "/home/dn-dev/benchmarking/benchmark.py", line 565, in <module>
    result = run(args, model, generator, eval_fn, benchmark_run)
  File "/home/dn-dev/benchmarking/benchmark.py", line 206, in run
    output_q = pybuda.initialize_pipeline(
  File "/home/dn-dev/tt-buda/pybuda/pybuda/run/api.py", line 441, in initialize_pipeline
    return _initialize_pipeline(training, output_queue, checkpoint_queue, sample_inputs, sample_targets, microbatch_count,
  File "/home/dn-dev/tt-buda/pybuda/pybuda/run/impl.py", line 414, in _initialize_pipeline
    _compile_devices(sequential, training=training, sample_inputs=sample_inputs, sample_targets=sample_targets, microbatch_count=microbatch_count, verify_cfg=verify_cfg)
  File "/home/dn-dev/tt-buda/pybuda/pybuda/run/impl.py", line 1248, in _compile_devices
    raise ret
RuntimeError: Backend compile failed: BackendCompileFailure.Invalid
Written out  results/perf_mobilenetv3_lg_na_tt_mb64_f1236.json  with summary
--------------------------------------------------------------------------------------------------------------------------------------------

**System (please complete the following information):**
 - Device: E75
 - Host information: AMD Ryzen 5 7600
 - OS : Ubuntu 22.04
 - Version ??

**Comment by milank94** [comment]
Hi @refill-dn

Please check if you are running the latest stable release for Ubuntu 22.04. Here is the package you can download: https://github.com/tenstorrent/tt-buda/releases/download/v0.12.3/pybuda-gs-v0.12.3-ubuntu-22-04-amd64-python3.10.zip

Setup instructions: https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md

Repo: https://github.com/tenstorrent/benchmarking/tree/v0.12.3

**Comment by milank94** [comment]
@refill-dn Were you able to make any progress with the provided guidance?

**Comment by refill** [comment]
@milank94  : it works!  

*****************************************************
 Ending benchmark at  Fri Jun  7 09:33:52 2024
*****************************************************
*****************************************************
 Device: Grayskull
 Total compilation time (s): 42.4038
 Peak host memory usage (MB): 4804.69
 Total runtime (s) for 30720 inputs: 22.3381
 Samples/sec: 1375.23
 Inference time (ms): 0.7
 Evaluation Score: 0.7572916666666667
 Batch size: 64
 Input shape: 3x224x224
 Datatype: Fp16_b
 Host device: AMD Ryzen 5 7600 6-Core Processor
 PyBUDA Version: 0.1.240509+dev.gs.a84d92c
 PyBUDA Version Date:
